# Generated by Django 5.2.4 on 2025-07-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=20, unique=True, verbose_name='Объем')),
            ],
        ),
        migrations.CreateModel(
            name='OlfactoryFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название ольфакторной семьи')),
                ('description', models.TextField(blank=True, verbose_name='Описание ольфакторной семьи')),
            ],
        ),
        migrations.CreateModel(
            name='OlfactoryNoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название ноты')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('show_in_filters', models.BooleanField(default=True, verbose_name='Показывать в фильтрах')),
                ('show_in_fragrance', models.BooleanField(default=True, verbose_name='Показывать в парфюме')),
                ('filter_name', models.CharField(blank=True, max_length=50, verbose_name='Название фильтра')),
                ('filter_slug', models.SlugField(blank=True, verbose_name='Слаг фильтра')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название ингредиента')),
                ('show_in_fragrance', models.BooleanField(default=False, verbose_name='Показывать в парфюме')),
                ('olfactory_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main.olfactoryfamily', verbose_name='Ольфакторная семья')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='OlfactoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название ноты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.olfactorynotecategory', verbose_name='Категория ноты')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название парфюма')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('detail_media', models.FileField(blank=True, help_text='Дополнительные медиафайлы для парфюма', upload_to='products/media/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('story', models.TextField(blank=True, verbose_name='История создания парфюма')),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_on_hero', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('show_in_featured', models.BooleanField(default=False, verbose_name='Показывать в разделе "Избранное"')),
                ('show_in_best_sellers', models.BooleanField(default=False, verbose_name='Показывать в разделе "Бестселлеры"')),
                ('base_notes', models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Base'}, related_name='base_notes', to='main.olfactoryfamily')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='main.category')),
                ('middle_notes', models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Middle'}, related_name='middle_notes', to='main.olfactoryfamily')),
                ('olfactory_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfumes', to='main.olfactoryfamily')),
                ('top_notes', models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Top'}, related_name='top_notes', to='main.olfactoryfamily')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes_capacities', to='main.capacity')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes_capacities', to='main.perfume')),
            ],
            options={
                'verbose_name': 'Ёмкость парфюма',
                'verbose_name_plural': 'Ёмкости парфюмов',
            },
        ),
        migrations.AddField(
            model_name='perfume',
            name='capacities',
            field=models.ManyToManyField(blank=True, related_name='perfumes', through='main.PerfumeCapacity', to='main.capacity'),
        ),
        migrations.CreateModel(
            name='PerfumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение парфюма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.perfume', verbose_name='Парфюм')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='main_catego_name_5111b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='perfumecapacity',
            unique_together={('perfume', 'capacity')},
        ),
    ]
