# Generated by Django 5.2.4 on 2025-07-25 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'объем', 'verbose_name_plural': 'объемы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='olfactoryfamily',
            options={'verbose_name': 'ольфакторная семья', 'verbose_name_plural': 'ольфакторные семьи'},
        ),
        migrations.AlterModelOptions(
            name='olfactorynote',
            options={'verbose_name': 'ольфакторная нота', 'verbose_name_plural': 'ольфакторные ноты'},
        ),
        migrations.AlterModelOptions(
            name='olfactorynotecategory',
            options={'verbose_name': 'категория нот', 'verbose_name_plural': 'категории нот'},
        ),
        migrations.AlterModelOptions(
            name='perfume',
            options={'verbose_name': 'парфюм', 'verbose_name_plural': 'парфюмы'},
        ),
        migrations.AlterModelOptions(
            name='perfumecapacity',
            options={'verbose_name': 'объем парфюма', 'verbose_name_plural': 'объемы парфюмов'},
        ),
        migrations.AlterModelOptions(
            name='perfumeimage',
            options={'verbose_name': 'изображение парфюма', 'verbose_name_plural': 'изображения парфюмов'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_in_fragrance',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='show_in_fragrance',
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_fragrances',
            field=models.BooleanField(default=False, verbose_name='Показывать в выпадающем меню парфюмов'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='show_in_fragrances',
            field=models.BooleanField(default=False, verbose_name='Показывать в выпадающем меню парфюмов'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='filter_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название фильтра (если отличается от категории)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='filter_slug',
            field=models.SlugField(blank=True, verbose_name='Слаг фильтра (для фронтенда)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_filters',
            field=models.BooleanField(default=False, verbose_name='Показывать в разделе фильтров'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='olfactoryfamily',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='olfactoryfamily',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название семьи'),
        ),
        migrations.AlterField(
            model_name='olfactorynote',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.olfactorynotecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='olfactorynotecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='base_notes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Base'}, related_name='base_notes', to='main.olfactorynote', verbose_name='Базовые ноты'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='capacities',
            field=models.ManyToManyField(blank=True, related_name='perfumes', through='main.PerfumeCapacity', to='main.capacity', verbose_name='Объемы'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='detail_media',
            field=models.FileField(blank=True, help_text='Загрузите изображение или видео для страницы деталей', upload_to='products/media/%Y/%m/%d', verbose_name='Медиа для деталей'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='middle_notes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Middle'}, related_name='middle_notes', to='main.olfactorynote', verbose_name='Средние ноты'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='olfactory_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfumes', to='main.olfactoryfamily', verbose_name='Ольфакторная семья'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='show_in_best_sellers',
            field=models.BooleanField(default=False, verbose_name='Показывать в разделе бестселлеров'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='show_in_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать в разделе избранных продуктов'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='show_on_hero',
            field=models.BooleanField(default=False, verbose_name='Показывать в главной секции (кнопка плюс)'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='story',
            field=models.TextField(blank=True, help_text='История создания парфюма', verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='top_notes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Top'}, related_name='top_notes', to='main.olfactorynote', verbose_name='Верхние ноты'),
        ),
        migrations.AlterField(
            model_name='perfumecapacity',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='perfumecapacity',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.capacity', verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='perfumecapacity',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perfume', verbose_name='Парфюм'),
        ),
        migrations.AlterField(
            model_name='perfumecapacity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='perfumecapacity',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='perfumeimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
